import { TenderStatus } from '../../types';
export const mockData = [
  {
    _id: '65faecb9ee16c743fc5cfe93',
    title: 'Architectural decoration of the embankment',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    submissionStart: '1711324800000',
    submissionEnd: '1711670400000',
    expectedDelivery: '1711756800000',
    category: ['1', '9', '0'],
    location: {
      nestedLocation: {
        _id: '65f181408de8fcd02bd9930b',
        name: 'Baošići',
      },
      geoPosition: {
        latitude: '42.4429',
        longitude: '18.627',
      },
      addressLine: 'wqertyuiytr 22',
      addressComment: 'wertyuiytr',
    },
    locationLeafId: '65f181408de8fcd02bd9930b',
    showEmail: true,
    files: ['1', '2', '3'],
    snapFiles: [],
    status: TenderStatus.IDEATION,
    ownerName: 'undefined undefined',
    ownerId: 'qwerty',
    createdAt: '1710943414607',
    modifiedAt: '1710943414607',
    organization: 'Testing organization',
    proposals: [
      {
        id: 1,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 2,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 2,
      },
    ],
  },
  {
    _id: '65faecb9ee16c743fc5cfe931',
    title: 'Architectural decoration of the embankment',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    submissionStart: '1711324800000',
    submissionEnd: '1711670400000',
    expectedDelivery: '1711756800000',
    category: ['1', '9', '0'],
    location: {
      nestedLocation: {
        _id: '65f181408de8fcd02bd9930b',
        name: 'Baošići',
      },
      geoPosition: {
        latitude: '42.4429',
        longitude: '18.627',
      },
      addressLine: 'wqertyuiytr 22',
      addressComment: 'wertyuiytr',
    },
    locationLeafId: '65f181408de8fcd02bd9930b',
    showEmail: true,
    files: ['1', '2', '3'],
    snapFiles: [],
    status: TenderStatus.VOTING,
    ownerName: 'undefined undefined',
    ownerId: 'qwerty',
    createdAt: '1710943414607',
    modifiedAt: '1710943414607',
    organization: 'Testing organization',
    proposals: [
      {
        id: 1,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 2,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 3,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 4,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 5,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 6,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 7,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 8,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 9,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 10,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 11,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 12,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
    ],
  },
  {
    _id: '65faecb9ee16c743fc5cfe932',
    title: 'Architectural decoration of the embankment',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    submissionStart: '1711324800000',
    submissionEnd: '1711670400000',
    expectedDelivery: '1711756800000',
    category: ['1', '9', '0'],
    location: {
      nestedLocation: {
        _id: '65f181408de8fcd02bd9930b',
        name: 'Baošići',
      },
      geoPosition: {
        latitude: '42.4429',
        longitude: '18.627',
      },
      addressLine: 'wqertyuiytr 22',
      addressComment: 'wertyuiytr',
    },
    locationLeafId: '65f181408de8fcd02bd9930b',
    showEmail: true,
    files: ['1', '2', '3'],
    snapFiles: [],
    status: TenderStatus.SELECTION,
    ownerName: 'undefined undefined',
    ownerId: 'qwerty',
    createdAt: '1710943414607',
    modifiedAt: '1710943414607',
    organization: 'Testing organization',
    proposals: [
      {
        id: 1,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 2,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 3,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 4,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 5,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 6,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 7,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 8,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 9,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },

      {
        id: 10,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 11,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 12,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
    ],
  },
  {
    _id: '65faecb9ee16c743fc5cfe933',
    title: 'Architectural decoration of the embankment',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    submissionStart: '1711324800000',
    submissionEnd: '1711670400000',
    expectedDelivery: '1711756800000',
    category: ['1', '9', '0'],
    location: {
      nestedLocation: {
        _id: '65f181408de8fcd02bd9930b',
        name: 'Baošići',
      },
      geoPosition: {
        latitude: '42.4429',
        longitude: '18.627',
      },
      addressLine: 'wqertyuiytr 22',
      addressComment: 'wertyuiytr',
    },
    locationLeafId: '65f181408de8fcd02bd9930b',
    showEmail: true,
    files: ['1', '2', '3'],
    snapFiles: [],
    status: TenderStatus.CLOSED,
    ownerName: 'undefined undefined',
    ownerId: 'qwerty',
    createdAt: '1710943414607',
    modifiedAt: '1710943414607',
    organization: 'Testing organization',
    proposals: [
      {
        id: 1,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: true,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 2,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 3,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 4,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },

      {
        id: 5,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 6,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 7,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 8,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 9,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 10,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 11,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
      {
        id: 12,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
    ],
  },
  {
    _id: '65faecb9ee16c743fc5cfe934',
    title: 'Architectural decoration of the embankment',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    submissionStart: '1711324800000',
    submissionEnd: '1711670400000',
    expectedDelivery: '1711756800000',
    category: ['1', '9', '0'],
    location: {
      nestedLocation: {
        _id: '65f181408de8fcd02bd9930b',
        name: 'Baošići',
      },
      geoPosition: {
        latitude: '42.4429',
        longitude: '18.627',
      },
      addressLine: 'wqertyuiytr 22',
      addressComment: 'wertyuiytr',
    },
    locationLeafId: '65f181408de8fcd02bd9930b',
    showEmail: true,
    files: ['1', '2', '3'],
    snapFiles: [],
    status: TenderStatus.DRAFT,
    ownerName: 'undefined undefined',
    ownerId: 'qwerty',
    createdAt: '1710943414607',
    modifiedAt: '1710943414607',
    organization: 'Testing organization',
    proposals: [],
  },
  {
    _id: '65faecb9ee16c743fc5cfe935',
    title: 'Architectural decoration of the embankment',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    submissionStart: '1711324800000',
    submissionEnd: '1711670400000',
    expectedDelivery: '1711756800000',
    category: ['1', '9', '0'],
    location: {
      nestedLocation: {
        _id: '65f181408de8fcd02bd9930b',
        name: 'Baošići',
      },
      geoPosition: {
        latitude: '42.4429',
        longitude: '18.627',
      },
      addressLine: 'wqertyuiytr 22',
      addressComment: 'wertyuiytr',
    },
    locationLeafId: '65f181408de8fcd02bd9930b',
    showEmail: true,
    files: ['1', '2', '3'],
    snapFiles: [],
    status: TenderStatus.CANCELLED,
    ownerName: 'undefined undefined',
    ownerId: 'qwerty',
    createdAt: '1710943414607',
    modifiedAt: '1710943414607',
    organization: 'Testing organization',
    proposals: [
      {
        id: 1,
        published: '1706787480000',
        thumbnail: '../../images/proposalThumb.png',
        selected: false,
        title: 'Mural depicting an evening stroll',
        description:
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. ',
        ownerId: 'qwerty',
        ownerName: 'Name name',
        ownerPicture: '',
        ownerOrg: 'testing org',
        likes: 1,
      },
    ],
  },
];
